title: Home
headerStyle: boxedWidgets
target: _blank
statusStyle: dot
layout:
  Productivity:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Development:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4
