---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wud-credentials
  namespace: wud
spec:
  encryptedData:
    admin-password: AgAkANDbAm3EN2uvboCekr9C0rOmL/EHh8mIoWkyHbccCAmhNngmbr1dfNTj5ENIpIYGNitHy0ZK85cXLEbAG4SAykI1DdcIIVF3godAVkSg56S5dZNzcPgXIsx1brubTFDUGRmQd4C3HcMVrYIsjyp3ajTA7rIK7Ig51ehJURQGgpzRWjv2HozlUWMPdYINJswNyIlwEj+9IZnGT5XwV4EKxi04rGk0yjPBZa3jtM0nIyjTBz9jLNR5sEpxEr9lWxVdnVZtirbEPWzl2obF/GijWX22L8alp5s+ORpGcHJDMnHm3Cf9z8WZGE/Y0GCk6OjNyjJi2JXmd5XqtpCfBEUCiEVucC5KVWgAHkPUul9+8c2nb8g+whKt2/vOvvC7f7RyysH/2e/UrNmvgv9BIW6Vtj/i6TeMcy52Wao6+5CHMtn3OXwsFZabggvKn8RFbtpWVFBjW5lcfofhVaxFbEFNSaulnoAARKGaDrkLSZ9Opgm66b1miL6GMe6sP09awxC/aFn/4NbTTpD9JY9xdf2ppE6/51DB8JKq4KmVIPmQ7xluO6WcfEABel7w0L8A0owR8UBFApD00FU0yUWYGvYgZRKF34DCgbaN0EQn5bTbcdaBEoL4c9QWuERRe0amTSvoJOf+7xFu0iWWa8XkPPFbeeJSnJFEm43FpxIT9SerN7ilUPzcEZ/tK5NSg/SkHBe/tNStk2EsoMfK+hjrSGLnVIgVt8WXpwG5kWl9WmiSEHKMVY8LsVbIQTdIxg==
    admin-user: AgDCTcwEpfPFF6b50lUU7pv/tdrhEZ5zV93t0fNsaVbviepS6w4+Lk7lmIw8acsLenF2nEFOZXK48w0DZ4cpt06KZMpo4u7UHYlCcf9raUARBUpWUiLtB9U9eSWWqo22PK+301PLISscmvIPvHTu2TrS6bBbPjYHBsPQZylw3BZ2984CW8TWW+Arq2eBfRGwVznxDYyR4N4CmGstq82qG4tzXunaeeYosyzdR9WamzPf7bMuqRLgVCpryeqwaz4VUYunc55clvNxrOvpRURINGj1z00TVCLNF6zbmVsv9ivKDhe1ODcKyiX2h8NqB42HGbk/7TIzt5B5s2DPfjFi8CmvoX5O/CvfFnbr4+uARGVqBp2gdZ+YT2LeG1pacqXRfvnas7WoPLlKx2LMiyVtnZd12cC34fjhw1qfNISZDnMdJuHII+rergAbc4ONqV/5Jat25Nwf5OiGDTOFH8xDAE/2PX7lXtntvjFWSrmiESSPC41l1c654l4IiHpckFAdT/TpPfsAHX5r4PFyuAXrlGEy+CVTu5NBZIUFiG4jphUUA251mrVcfi+ObANJ1I3OMMjKLcdtf2xRoWkdiLCt6A8a/qzbvpmJp52dBz7U0HCOQf2FMa0lxTkpq8XHMIIQYTp5oJ5JTY7lPoNiNM75sJ0z7dZrngxLmyzhFTEQoL6L2xRJOMpRiTEHI0/q1MAuOeYEx47+zA==
  template:
    metadata:
      name: wud-credentials
      namespace: wud
    type: Opaque
