---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-credentials
  namespace: immich
spec:
  encryptedData:
    db-password: AgCNVBbZqZVqHWEHHEPkYbyajVleSJw/9sxK6qYW91JbqBw/k9rZvTwF3o34Bp/7Dp0Wnm+K27JF1y6NxT+HDH44O/hPBijwJz7ttkmX6ZwIV0e6KgK8EMPfFRRY4Ov0UT9MUJckxQF0O7ux64BDbACll2OANwPyNuI8eO2+riPAoUmKmKzE25VV3oSe5noDmIMgaQv65vTGiY18ET0hIES8GdfgNS8VsDgygZfqWJpK+nMlGqKAGX/Yv4m5Mp0UeWSam0VQxrmehgruKhNj75n7L6mI/XPEmSc04rmcWrblDHqqSNNqChOXHA1dyLh9pKGyuaVBgKUkqwAe3rODR0SGIQ+TgnrTMLtBFKCSX5qFJ6rASKBL6pDqYqKyCL5TXP743jo+DpIOHK34rWY6G0hLaWrdadIn+2HE1SHm2dNdwXR/YH6g4n6EZy5IbfGDpNjdn5YoJgAenzh4XRazYlRXoOWNZvIx30LZMVlV5n/oaFAkGbbDoLutmioiFNMecw9rPQk4cWijIi+PYnDPis88EuvjC1YYfs1XZue4OwkbWznN2vO/Cytqlsw1JCUMSTEvjLMjrMeGh/VBK3nFo1e+HZUZcoBSunIwPm+A1H3cjYMnhOXtn6ATPIfvEnGpUF6rKI8HYVcaJJZDoWWhxuNBs7W6vt5TwxhuD1jcMewk7/wmGAqSC3S3OmCtNLzQkJbNSK6+o6Z7cgYRyYVVXMsM+xMekMNu
  template:
    metadata:
      name: immich-credentials
      namespace: immich
    type: Opaque
